export const standardSkills = [
  ["skill.acrobatics", "Acrobatics"],
  ["skill.appraise", "Appraise"],
  ["skill.bluff", "Bluff"],
  ["skill.climb", "Climb"],
  ["skill.craft", "Craft"],
  ["skill.diplomacy", "Diplomacy"],
  ["skill.disable-device", "Disable Device"],
  ["skill.disguise", "Disguise"],
  ["skill.escape-artist", "Escape Artist"],
  ["skill.fly", "Fly"],
  ["skill.handle-animal", "Handle Animal"],
  ["skill.heal", "Heal"],
  ["skill.intimidate", "Intimidate"],
  ["skill.knowledge", "Knowledge"],
  ["skill.linguistics", "Linguistics"],
  ["skill.perception", "Perception"],
  ["skill.perform", "Perform"],
  ["skill.profession", "Profession"],
  ["skill.ride", "Ride"],
  ["skill.sense-motive", "Sense Motive"],
  ["skill.sleight-of-hand", "Sleight of Hand"],
  ["skill.spellcraft", "Spellcraft"],
  ["skill.stealth", "Stealth"],
  ["skill.survival", "Survival"],
  ["skill.swim", "Swim"],
  ["skill.use-magic-device", "Use Magic Device"],
] as const;

export const standardSkillIds = standardSkills.map(([id]) => id);
